// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Shared.Persistence;

public partial class Account
{
    public string Value { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}