// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Application.Shared.Persistence;

public partial class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<Budget> Budgets { get; set; }

    public virtual DbSet<BudgetItem> BudgetItems { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<Year> Years { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.Value);

            entity.ToTable("Account");
        });

        modelBuilder.Entity<Budget>(entity =>
        {
            entity.ToTable("Budget");

            entity.HasIndex(e => new { e.Year, e.Month, e.BudgetItemId }, "IX_Budget_Year_Month_BudgetItem_Id").IsUnique();

            entity.Property(e => e.BudgetItemId).HasColumnName("BudgetItem_Id");

            entity.HasOne(d => d.BudgetItem).WithMany(p => p.Budgets)
                .HasForeignKey(d => d.BudgetItemId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.YearNavigation).WithMany(p => p.Budgets)
                .HasForeignKey(d => d.Year)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<BudgetItem>(entity =>
        {
            entity.ToTable("BudgetItem");

            entity.HasIndex(e => e.Description, "IX_BudgetItem_Description").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.Type).IsRequired();
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.ToTable("Transaction");

            entity.Property(e => e.Account).IsRequired();
            entity.Property(e => e.BudgetId)
                .IsRequired()
                .HasColumnName("Budget_Id");
            entity.Property(e => e.Date).IsRequired();

            entity.HasOne(d => d.AccountNavigation).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.Account)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Budget).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.BudgetId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Year>(entity =>
        {
            entity.HasKey(e => e.Value);

            entity.ToTable("Year");

            entity.Property(e => e.Value).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}