// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Shared.Persistence;

public partial class Budget
{
    public string Id { get; set; }

    public int Year { get; set; }

    public int Month { get; set; }

    public double Amount { get; set; }

    public int CategoryId { get; set; }

    public virtual Category Category { get; set; }
}