// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Shared.Persistence;

public partial class Budget
{
    public string Id { get; set; }

    public int BudgetItemId { get; set; }

    public int Year { get; set; }

    public int Month { get; set; }

    public double Amount { get; set; }

    public virtual BudgetItem BudgetItem { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual Year YearNavigation { get; set; }
}