// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Shared.Persistence;

public partial class Category
{
    public int Id { get; set; }

    public string Type { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Budget> Budgets { get; set; } = new List<Budget>();
}