// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Shared.Persistence;

public partial class Transaction
{
    public string Id { get; set; }

    public string Date { get; set; }

    public string BudgetId { get; set; }

    public string Account { get; set; }

    public double Amount { get; set; }

    public string Description { get; set; }

    public string EffectiveDate { get; set; }

    public virtual Account AccountNavigation { get; set; }

    public virtual Budget Budget { get; set; }
}